
/* File generated by gen_cfile.py. Should not be modified. */

#include "master.h"

/**************************************************************************/
/* Declaration of mapped variables                                        */
/**************************************************************************/
UNS8 test[] =		/* Mapped at index 0x2001, subindex 0x01 - 0x10 */
  {
    0x0,	/* 0 */
    0x0,	/* 0 */
    0x0,	/* 0 */
    0x0,	/* 0 */
    0x0,	/* 0 */
    0x0,	/* 0 */
    0x0,	/* 0 */
    0x0,	/* 0 */
    0x0,	/* 0 */
    0x0,	/* 0 */
    0x0,	/* 0 */
    0x0,	/* 0 */
    0x0,	/* 0 */
    0x0,	/* 0 */
    0x0,	/* 0 */
    0x0	/* 0 */
  };

/**************************************************************************/
/* Declaration of value range types                                       */
/**************************************************************************/

#define valueRange_EMC 0x9F /* Type for index 0x1003 subindex 0x00 (only set of value 0 is possible) */
UNS32 master_valueRangeTest (UNS8 typeValue, void * value)
{
  switch (typeValue) {
    case valueRange_EMC:
      if (*(UNS8*)value != (UNS8)0) return OD_VALUE_RANGE_EXCEEDED;
      break;
  }
  return 0;
}

/**************************************************************************/
/* The node id                                                            */
/**************************************************************************/
/* node_id default value.*/
UNS8 master_bDeviceNodeId = 0x00;

/**************************************************************************/
/* Array of message processing information */

const UNS8 master_iam_a_slave = 0;

TIMER_HANDLE master_heartBeatTimers[1];

/*
$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$

                               OBJECT DICTIONARY

$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$
*/

/* index 0x1000 :   Device Type. */
                    UNS32 master_obj1000 = 0x0;	/* 0 */
                    subindex master_Index1000[] = 
                     {
                       { RO, uint32, sizeof (UNS32), (void*)&master_obj1000 }
                     };

/* index 0x1001 :   Error Register. */
                    UNS8 master_obj1001 = 0x0;	/* 0 */
                    subindex master_Index1001[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&master_obj1001 }
                     };

/* index 0x1003 :   Pre-defined Error Field */
                    UNS8 master_highestSubIndex_obj1003 = 0; /* number of subindex - 1*/
                    UNS32 master_obj1003[] = 
                    {
                      0x0	/* 0 */
                    };
                    ODCallback_t master_Index1003_callbacks[] = 
                     {
                       NULL,
                       NULL,
                     };
                    subindex master_Index1003[] = 
                     {
                       { RW, valueRange_EMC, sizeof (UNS8), (void*)&master_highestSubIndex_obj1003 },
                       { RO, uint32, sizeof (UNS32), (void*)&master_obj1003[0] }
                     };

/* index 0x1005 :   SYNC COB ID */
                    UNS32 master_obj1005 = 0x0;   /* 0 */

/* index 0x1006 :   Communication / Cycle Period */
                    UNS32 master_obj1006 = 0x0;   /* 0 */

/* index 0x100C :   Guard Time */ 
                    UNS16 master_obj100C = 0x0;   /* 0 */

/* index 0x100D :   Life Time Factor */ 
                    UNS8 master_obj100D = 0x0;   /* 0 */

/* index 0x1014 :   Emergency COB ID */
                    UNS32 master_obj1014 = 0x80 + 0x00;   /* 128 + NodeID */

/* index 0x1016 :   Consumer Heartbeat Time */
                    UNS8 master_highestSubIndex_obj1016 = 0;
                    UNS32 master_obj1016[]={0};

/* index 0x1017 :   Producer Heartbeat Time */ 
                    UNS16 master_obj1017 = 0x0;   /* 0 */

/* index 0x1018 :   Identity. */
                    UNS8 master_highestSubIndex_obj1018 = 4; /* number of subindex - 1*/
                    UNS32 master_obj1018_Vendor_ID = 0x0;	/* 0 */
                    UNS32 master_obj1018_Product_Code = 0x0;	/* 0 */
                    UNS32 master_obj1018_Revision_Number = 0x0;	/* 0 */
                    UNS32 master_obj1018_Serial_Number = 0x0;	/* 0 */
                    subindex master_Index1018[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&master_highestSubIndex_obj1018 },
                       { RO, uint32, sizeof (UNS32), (void*)&master_obj1018_Vendor_ID },
                       { RO, uint32, sizeof (UNS32), (void*)&master_obj1018_Product_Code },
                       { RO, uint32, sizeof (UNS32), (void*)&master_obj1018_Revision_Number },
                       { RO, uint32, sizeof (UNS32), (void*)&master_obj1018_Serial_Number }
                     };

/* index 0x1200 :   Server SDO Parameter. */
                    UNS8 master_highestSubIndex_obj1200 = 2; /* number of subindex - 1*/
                    UNS32 master_obj1200_COB_ID_Client_to_Server_Receive_SDO = 0x600;	/* 1536 */
                    UNS32 master_obj1200_COB_ID_Server_to_Client_Transmit_SDO = 0x580;	/* 1408 */
                    subindex master_Index1200[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&master_highestSubIndex_obj1200 },
                       { RO, uint32, sizeof (UNS32), (void*)&master_obj1200_COB_ID_Client_to_Server_Receive_SDO },
                       { RO, uint32, sizeof (UNS32), (void*)&master_obj1200_COB_ID_Server_to_Client_Transmit_SDO }
                     };

/* index 0x1800 :   Transmit PDO 1 Parameter. */
                    UNS8 master_highestSubIndex_obj1800 = 5; /* number of subindex - 1*/
                    UNS32 master_obj1800_COB_ID_used_by_PDO = 0x180;	/* 384 */
                    UNS8 master_obj1800_Transmission_Type = 0x0;	/* 0 */
                    UNS16 master_obj1800_Inhibit_Time = 0x0;	/* 0 */
                    UNS8 master_obj1800_Compatibility_Entry = 0x0;	/* 0 */
                    UNS16 master_obj1800_Event_Timer = 0x0;	/* 0 */
                    ODCallback_t master_Index1800_callbacks[] = 
                     {
                       NULL,
                       NULL,
                       NULL,
                       NULL,
                       NULL,
                       NULL,
                     };
                    subindex master_Index1800[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&master_highestSubIndex_obj1800 },
                       { RW, uint32, sizeof (UNS32), (void*)&master_obj1800_COB_ID_used_by_PDO },
                       { RW, uint8, sizeof (UNS8), (void*)&master_obj1800_Transmission_Type },
                       { RW, uint16, sizeof (UNS16), (void*)&master_obj1800_Inhibit_Time },
                       { RW, uint8, sizeof (UNS8), (void*)&master_obj1800_Compatibility_Entry },
                       { RW, uint16, sizeof (UNS16), (void*)&master_obj1800_Event_Timer }
                     };

/* index 0x1A00 :   Transmit PDO 1 Mapping. */
                    UNS8 master_highestSubIndex_obj1A00 = 0; /* number of subindex - 1*/
                     subindex master_Index1A00[] = 
                     {
                       { RW, uint8, sizeof (UNS8), (void*)&master_highestSubIndex_obj1A00 }
                     };

/* index 0x2001 :   Mapped variable test */
                    UNS8 master_highestSubIndex_obj2001 = 16; /* number of subindex - 1*/
                    subindex master_Index2001[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&master_highestSubIndex_obj2001 },
                       { RW, uint8, sizeof (UNS8), (void*)&test[0] },
                       { RW, uint8, sizeof (UNS8), (void*)&test[1] },
                       { RW, uint8, sizeof (UNS8), (void*)&test[2] },
                       { RW, uint8, sizeof (UNS8), (void*)&test[3] },
                       { RW, uint8, sizeof (UNS8), (void*)&test[4] },
                       { RW, uint8, sizeof (UNS8), (void*)&test[5] },
                       { RW, uint8, sizeof (UNS8), (void*)&test[6] },
                       { RW, uint8, sizeof (UNS8), (void*)&test[7] },
                       { RW, uint8, sizeof (UNS8), (void*)&test[8] },
                       { RW, uint8, sizeof (UNS8), (void*)&test[9] },
                       { RW, uint8, sizeof (UNS8), (void*)&test[10] },
                       { RW, uint8, sizeof (UNS8), (void*)&test[11] },
                       { RW, uint8, sizeof (UNS8), (void*)&test[12] },
                       { RW, uint8, sizeof (UNS8), (void*)&test[13] },
                       { RW, uint8, sizeof (UNS8), (void*)&test[14] },
                       { RW, uint8, sizeof (UNS8), (void*)&test[15] }
                     };

/**************************************************************************/
/* Declaration of pointed variables                                       */
/**************************************************************************/

const indextable master_objdict[] = 
{
  { (subindex*)master_Index1000,sizeof(master_Index1000)/sizeof(master_Index1000[0]), 0x1000},
  { (subindex*)master_Index1001,sizeof(master_Index1001)/sizeof(master_Index1001[0]), 0x1001},
  { (subindex*)master_Index1018,sizeof(master_Index1018)/sizeof(master_Index1018[0]), 0x1018},
  { (subindex*)master_Index1200,sizeof(master_Index1200)/sizeof(master_Index1200[0]), 0x1200},
  { (subindex*)master_Index1800,sizeof(master_Index1800)/sizeof(master_Index1800[0]), 0x1800},
  { (subindex*)master_Index1A00,sizeof(master_Index1A00)/sizeof(master_Index1A00[0]), 0x1A00},
  { (subindex*)master_Index2001,sizeof(master_Index2001)/sizeof(master_Index2001[0]), 0x2001},
};

const indextable * master_scanIndexOD (UNS16 wIndex, UNS32 * errorCode, ODCallback_t **callbacks)
{
	int i;
	*callbacks = NULL;
	switch(wIndex){
		case 0x1000: i = 0;break;
		case 0x1001: i = 1;break;
		case 0x1018: i = 2;break;
		case 0x1200: i = 3;break;
		case 0x1800: i = 4;*callbacks = master_Index1800_callbacks; break;
		case 0x1A00: i = 5;break;
		case 0x2001: i = 6;break;
		default:
			*errorCode = OD_NO_SUCH_OBJECT;
			return NULL;
	}
	*errorCode = OD_SUCCESSFUL;
	return &master_objdict[i];
}

/* 
 * To count at which received SYNC a PDO must be sent.
 * Even if no pdoTransmit are defined, at least one entry is computed
 * for compilations issues.
 */
s_PDO_status master_PDO_status[1] = {s_PDO_status_Initializer};

const quick_index master_firstIndex = {
  3, /* SDO_SVR */
  0, /* SDO_CLT */
  0, /* PDO_RCV */
  0, /* PDO_RCV_MAP */
  4, /* PDO_TRS */
  5 /* PDO_TRS_MAP */
};

const quick_index master_lastIndex = {
  3, /* SDO_SVR */
  0, /* SDO_CLT */
  0, /* PDO_RCV */
  0, /* PDO_RCV_MAP */
  4, /* PDO_TRS */
  5 /* PDO_TRS_MAP */
};

const UNS16 master_ObjdictSize = sizeof(master_objdict)/sizeof(master_objdict[0]); 

CO_Data master_Data = CANOPEN_NODE_DATA_INITIALIZER(master);

