
/* File generated by gen_cfile.py. Should not be modified. */

#ifndef MASTER_H
#define MASTER_H

#include "data.h"

/* Prototypes of function provided by object dictionnary */
UNS32 master_valueRangeTest (UNS8 typeValue, void * value);
const indextable * master_scanIndexOD (UNS16 wIndex, UNS32 * errorCode, ODCallback_t **callbacks);

/* Master node data struct */
extern CO_Data master_Data;
extern UNS8 test[16];		/* Mapped at index 0x2001, subindex 0x01 - 0x10 */

#endif // MASTER_H
